### PR TITLE
gives stream1 spurious undefineds

### PR DESCRIPTION
**Pull request by calvinmetcalf**
failing test is attached

### CODE REVIEW

**Comment by mcollina** [comment]
ouch, let me see what's hapenning.

**Comment by mcollina** [comment]
Fixed :).

**Comment by calvinmetcalf** [comment]
great! thanks

**Comment by calvinmetcalf** [comment]
are you going to publish a new version ?

**Comment by mcollina** [comment]
v0.5.0 is out :).

**Pull request merged**
